name: AzureLogintest
on: 
   push:
        paths:
            - ".github/workflows/deployDev.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout         
          uses: actions/checkout@v2

        - name: Log in with          
          uses: azure/login@v1
          with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'

# deploy ARM template with inline AZ CLI command
        - name: Deploy ARM Template
          uses: azure/CLI@v1
      # define required arguments for AZ CLI command 
          env:
            RESOURCE_GROUP: DevOpsBootCamp
            TEMPLATEFILE: container-webapp-template.json 
           with:
      # Execute AZ CLI command
                inlineScript: |
                    az deployment group create --resource-group $RESOURCE_GROUP --template-file $TEMPLATEFILE
